# Generated by Django 2.1 on 2019-03-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0003_auto_20190318_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
